version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - bot
  ignore:
  - dependency-name: "@storybook/addon-viewport"
    versions:
    - 6.1.15
    - 6.1.21
    - 6.2.8
  - dependency-name: "@storybook/vue"
    versions:
    - 6.1.21
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.21
    - 6.2.8
  - dependency-name: gitmoji-cli
    versions:
    - 3.3.1
  - dependency-name: babel-jest
    versions:
    - 26.6.3
  - dependency-name: "@vue/eslint-config-airbnb"
    versions:
    - 5.3.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: pug-code-gen
    versions:
    - 3.0.2
  - dependency-name: core-js
    versions:
    - 3.8.3
    - 3.9.0
  - dependency-name: "@storybook/theming"
    versions:
    - 6.1.17
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: "@vue/cli-plugin-unit-jest"
    versions:
    - 4.5.11
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.1.15
  commit-message:
    prefix: "⬆️"
