<template>
  <div class="toast" :class="computedClasses">
    <p class="toast__text">
      <slot></slot>
    </p>
    <section v-if="hasLabels" class="toast__controls">
      <button
        v-if="secondaryLabel"
        type="button"
        class="toast__control toast__control--secondary"
        @click="secondaryClick"
        v-text="secondaryLabel"
      />
      <button
        v-if="primaryLabel"
        type="button"
        class="toast__control toast__control--primary"
        @click="primaryClick"
        v-text="primaryLabel"
      />
    </section>
  </div>
</template>

<script>
export default {
  name: 'HdToast',
  props: {
    secondaryLabel: String,
    primaryLabel: String,
  },
  data: () => ({
    isOpen: false,
    isClosing: false,
  }),
  mounted() {
    this.$on('open', this.open);
  },
  computed: {
    hasLabels() {
      return Boolean(this.primaryLabel || this.secondaryLabel);
    },
    computedClasses() {
      return {
        'toast--isOpen': this.isOpen,
        'toast--isClosing': this.isClosing,
      };
    },
  },
  methods: {
    open() {
      this.isOpen = true;
    },
    close() {
      this.isClosing = true;
      setTimeout(() => {
        this.isOpen = false;
        this.isClosing = false;
        this.$emit('close');
      }, 500);
    },
    primaryClick() {
      this.$emit('primaryClick');
    },
    secondaryClick() {
      this.$emit('secondaryClick');
      this.close();
    },
  },
};
</script>

<style lang="scss">
@import 'homeday-blocks/src/styles/mixins.scss';
$toastWidth: 288px;

.toast {
  // Position
  display: none;
  position: fixed;
  top: 50%;
  bottom: auto;
  transform: translateY(-50%);
  z-index: 99;
  left: 0;
  right: 0;
  margin: auto;

  @media (min-width: $break-tablet) {
    transform: none;
    left: auto;
    right: $sp-m;
    top: $sp-m;
  }

  @media (min-width: $break-tablet) {
    right: $sp-l;
    top: $sp-m;
  }

  // Appereance
  width: $toastWidth;
  background: $white;
  border-radius: $default-border-radius;
  border: 1px solid #e1e1e1;
  box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.25);
  @include font('xsheadline');

  &--isOpen {
    display: block;
    animation: slide-in-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  }
  &--isClosing {
    animation: slide-out-top 0.45s cubic-bezier(0.755, 0.05, 0.855, 0.06) both;
  }
  &__text {
    padding: $sp-s $sp-m;

    border-bottom: 1px solid #e1e1e1;
  }
  &__controls {
    display: flex;
    flex-grow: 1;
  }

  &__control {
    @include font('xsheadline');
    width: 100%;
    height: 42px;
    border: none;
    outline: none;
    text-align: center;
    background: $white;

    &--primary {
      background: getShade($secondary-color, 110);
      color: $white;
      position: relative;
      cursor: pointer;
      transition: all $time-s ease-in-out;

      // Fake the blue border
      &:after {
        content: '';
        background: transparent;
        width: 100%;
        position: absolute;
        height: 100%;
        top: 0;
        left: 0;
        margin-left: -1px;
        border-right: 1px solid getShade($secondary-color, 110);
        border-left: 1px solid getShade($secondary-color, 110);
        border-bottom: 1px solid getShade($secondary-color, 110);

        border-bottom-right-radius: $default-border-radius;
        border-bottom-right-radius: $default-border-radius;
      }

      &:hover {
        background-color: getShade($secondary-color, 110);

        &:after {
          border-color: getShade($secondary-color, 110);
        }
      }
    }

    &--secondary {
      color: getShade($quaternary-color, 80);
    }
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2018-8-16 17:47:24
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-elliptic-top-fwd
 * ----------------------------------------
 */
@keyframes slide-in-top {
  0% {
    transform: translateY(-1000px);
    opacity: 0;
  }
  100% {
    transform: translateY(0);
    opacity: 1;
  }
}

@keyframes slide-out-top {
  0% {
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    transform: translateY(-1000px);
    opacity: 0;
  }
}

@keyframes pulsate-fwd {
  0% {
    transform: scale(1);
  }
  50% {
    transform: scale(1.05);
  }
  100% {
    transform: scale(1);
  }
}
</style>
